#!/bin/bash
#
#  create an initial (empty) database for Grouper 
#  and set an initial password for the mysql root and grouper users
#

sudo docker run --name mysqlserver  \
	-e MYSQL_ROOT_PASSWORD=changeme \
        -e MYSQL_DATABASE=grouper \
        -e MYSQL_USER=grouper \
        -e MYSQL_PASSWORD=changeme \
	-v `pwd`/mysql_persistant_data:/var/lib/mysql \
	-d mysql:5.7  \
	--character-set-server=utf8     \
	--collation-server=utf8_bin     \
	--skip-character-set-client-handshake     
