#!/bin/bash
#
#  create an initial (empty) database for Grouper 
#  and set an initial password for the mysql root and grouper users
#

# first remove whatver is in the directory because mysql will not touch it if there are files present
rm -rf `pwd`/mysql_persistant_data/*

# now build an empty database
sudo docker run --name mysqlserver  \
 -v `pwd`/mysqlconf.d:/etc/mysql/conf.d \
 -e MYSQL_ROOT_PASSWORD=changeme \
 -e MYSQL_DATABASE=grouper \
 -e MYSQL_USER=grouper \
 -e MYSQL_PASSWORD=changeme \
 -v `pwd`/mysql_persistant_data:/var/lib/mysql \
 -d mysql:5.7    \
	--character-set-server=utf8     \
	--collation-server=utf8_bin     \
	--skip-character-set-client-handshake      
