#!/bin/bash
#
# run file mySQL server used by Grouper
#
# this presumes that a database has already been created and
# the database files are located at 
#       `pwd`/mysql_persistant_data:/var/lib/mysql
# If you don't already have a populated database, run the script
#       create-mysql-db
# to create one
#

sudo docker run --name mysqlserver  \
    -v `pwd`/mysqlconf.d:/etc/mysql/conf.d \
	-e MYSQL_ROOT_PASSWORD=changeme \
	-v `pwd`/mysql_persistant_data:/var/lib/mysql \
    -p 127.0.0.1:3306:3306 \
	-d mysql:5.7      \
	     --character-set-server=utf8     \
	     --collation-server=utf8_bin     \
	     --skip-character-set-client-handshake       

